baseURL = "https://fuad3ziz.com/"
defaultContentLanguage = "ar"
languageCode = "ar-sa"
title = "مدونة عزيز"

# --- إعدادات الترقيم الجديدة ---
[pagination]
  pagerSize = 6 # عدد العناصر في كل صفحة

# --- بقية الإعدادات ---
[params]
  description = "مدونة متخصصة في أنظمة الشبكات، الأمن السيبراني، الأنظمة الأمنية المتطورة، التسويق والتجارة الالكترونية، مع التركيز على تعزيز الأمان الرقمي والتعليم التقني."
  author = "Fuad Abdulaziz"
  logo = "images/logo-feather.svg"

[languages]
  [languages.ar]
    languageName = "العربية"
    weight = 1
    [languages.ar.params]
    rtl = true

[permalinks]
  posts = "/:year/:month/:title/"

[menu]
  [[menu.main]]
    name = "الرئيسية"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "المقالات"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "عني"
    url = "/about/"
    weight = 3

  # --- إعدادات البحث ---
# 1. تعريف صيغة مخرجات جديدة اسمها "json"
[outputFormats.json]
  baseName = "index"
  mediaType = "application/json"
  isPlainText = true

# 2. تحديد أنواع الصفحات التي نريد إنشاء مخرجات لها
[outputs]
  home = ["HTML", "JSON"] # للصفحة الرئيسية
  section = ["HTML", "RSS"] # للأقسام (مثل /posts/)